apiVersion: v1
kind: ConfigMap
metadata:
  name: issuer-web-config
data:
  _features.conf: |
    enabledFeatures = [
        entra
    ]
  web.conf: |
    webHost = "0.0.0.0"
    webPort = 3000
  issuer-service.conf: |
    baseUrl = "http://10.140.0.5"
  authentication-service.conf: |
    name = "keycloak"
    authorizeUrl = "https://keycloak.walt-test.cloud/realms/waltid-keycloak-ktor/protocol/openid-connect/auth"
    accessTokenUrl = "https://keycloak.walt-test.cloud/realms/waltid-keycloak-ktor/protocol/openid-connect/token"
    clientId = "issuer_api"
  credential-issuer-metadata.conf: |
    supportedCredentialTypes = {
      "turing_certificate_vc+sd-jwt" = {
          format = "vc+sd-jwt",
          cryptographic_binding_methods_supported = ["jwk"]
          credential_signing_alg_values_supported = ["RS256"]
          vct = "http://10.140.0.5/identity_credential"
      }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: issuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuer
  template:
    metadata:
      labels:
        app: issuer
      annotations:
        deployment/id: '_DEFAULT_DEPLOYMENT_'
    spec:
      containers:
        - name: issuer
          image: waltid/issuer-api:v1.0.2502181817
          volumeMounts:
            - name: issuer-web-config
              mountPath: '/waltid-issuer-api/config'
              readOnly: true
          env:
            - name: ISSUER_API_HOST
              value: '10.140.0.5'
          ports:
            - containerPort: 3000
              name: http-api
          livenessProbe:
            httpGet:
              path: /livez
              port: http-api
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /livez
              port: http-api
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: issuer-web-config
          configMap:
            name: issuer-web-config
---
kind: Service
apiVersion: v1
metadata:
  name: issuer
  annotations:
    networking.gke.io/load-balancer-type: 'Internal'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: issuer
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: issuer
#   annotations:
#     kubernetes.io/ingress.class: 'nginx'
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   tls:
#     - hosts:
#         - issuer.portal.walt.id
#       secretName: issuer-tls-secret
#   rules:
#     - host: issuer.portal.walt.id
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: issuer
#                 port:
#                   name: http
