supportedCredentialTypes = {
    "turing_certificate_vc+sd-jwt" = {
        format = "vc+sd-jwt",
        cryptographic_binding_methods_supported = ["jwk"]
        credential_signing_alg_values_supported = ["RS256"]
        vct = "http://10.140.0.48/identity_credential"
    }
}
